[workspace]
members = [
    "mullvad-daemon",
    "mullvad-cli",
    "mullvad-problem-report",
    "mullvad-ipc-client",
    "mullvad-paths",
    "mullvad-types",
    "mullvad-rpc",
    "mullvad-tests",
    "talpid-openvpn-plugin",
    "talpid-core",
    "talpid-ipc",
]

[patch.crates-io]
openssl-sys = { git = "https://github.com/mullvad/rust-openssl" }
